name: Publish PowerShell Module

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:

    runs-on: windows-latest

    env:
      Project_Path: "./power-p4/src/PowerP4Module.csproj"
      Output_Directory: "./Release"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .Net Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Module
      run: dotnet build $env:PROJECT_PATH /p:Configuration=Publish /p:Platform="AnyCPU" -o $env:OUTPUT_DIRECTORY
      shell: powershell
      env:
        PROJECT_PATH: ${{ env.Project_Path }}
        OUTPUT_DIRECTORY: ${{ env.Output_Directory }}
  
    - name: Build and publish
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
        OUTPUT_DIRECTORY: ${{ env.Output_Directory }}
      shell: pwsh        
      run: |
        Move-Item .\power-p4\power-p4.psd1 $env:OUTPUT_DIRECTORY
        Set-Location $env:OUTPUT_DIRECTORY
        Update-ModuleManifest -Path .\power-p4.psd1 -RootModule .\
        Publish-Module -Path power-p4 -NuGetApiKey $env:NUGET_KEY -Verbose